### ISSUE TITLE
wildcard pattern issues on windows

### ISSUE THREAD

**Issue by bryanbcook** [bryanbcook/azdevops-testplan-extension#106]
No test results are found on a windows build agent when using a wildcard pattern.

Given the following folder structure:

```
c:\examples\a\TestResults.xml
c:\examples\b\TestResults.xml
c:\examples\c\TestResults.xml
```

The following syntax:

```yaml
- task: PublishTestPlanResults@0
  inputs:
     testPlan: 'Primary Test Plan'
     testResultFiles: c:\examples\**\TestResults.xml
     testResultFormat: nunit
```

produces:

```
##vso[task.debug]testResultFiles=c:\examples\*\TestResults.xml
##vso[task.debug]check path : c:\examples\*\TestResults.xml
##vso[task.debug]task result: Failed
##vso[task.issue type=error;source=TaskInternal;]Not found testResultFile(s): c:\examples\*\TestResults.xml
##vso[task.complete result=Failed;]Not found testResultFile(s): c:\examples\*\TestResults.xml
```
