### ISSUE TITLE
Add support for attachments

### ISSUE THREAD

**Issue by bryanbcook** [bryanbcook/azdevops-testplan-extension#21]
Ideally, attachments included in the test results should be automatically uploaded into the test run per test-case.

```yaml
- task: PublishTestPlanResults@0
  inputs:
    ....
    publishTestAttachments: # boolean, should default to true
    testAttachmentDirectory: # string. should default to testResultDirectory
```
