### ISSUE TITLE
Relative test result file path not being applied correctly

### ISSUE THREAD

**Issue by C0nquistadore** [bryanbcook/azdevops-testplan-extension#50]
**Description**

Hi, first of all, great work on the extension! It really helps a lot when running on Linux where the VSTest task is not supported.

When setting the properties `Test Results Directory` and `Test Result Files`, I've encountered an issue in the way the path is combined.

![image](https://github.com/user-attachments/assets/c3549732-12ea-46b5-9d6c-ed85a5a7c425)

The `TargetTestResultsFolderSearch` variables resolves to `$(Agent.TempDirectory)/TestResults/Search` and that resolves to `/home/svc_prc_inttest/azagent/_work/_temp/TestResults/Search/mstest`

The result is
```
Not found testResultFile(s): /home/svc_prc_inttest/azagent/_work/_temp/TestResults/Search/mstest/home/svc_prc_inttest/azagent/_work/r1/a/SearchTests.trx
```

Here you can see the `Test Results Directory` property is combined with `/home/svc_prc_inttest/azagent/_work/r1/a` (which is the default working directory I assume) and then with the `Test Result Files` property (the file name).

**Environment Details**

I am using Azure DevOps Server 2022.2 RC (AzureDevopsServer_20240423.2) with a deployment job running on a linux agent.

- build-agent: self-hosted (linux)
- test-format: mstest
- test-lanugage: C#
- pipeline-format: Designer-based (Classic)

**Pipeline Output**

```
2024-11-07T06:33:07.6158532Z ##[debug]testResultFormat=mstest
2024-11-07T06:33:07.6163521Z ##[debug]testResultDirectory=/home/svc_prc_inttest/azagent/_work/_temp/TestResults/Search/mstest
2024-11-07T06:33:07.6168392Z ##[debug]testResultFiles=/home/svc_prc_inttest/azagent/_work/r1/a/SearchTests.trx
2024-11-07T06:33:07.6171479Z ##[debug]check path : /home/svc_prc_inttest/azagent/_work/_temp/TestResults/Search/mstest/home/svc_prc_inttest/azagent/_work/r1/a/SearchTests.trx
2024-11-07T06:33:07.6192983Z ##[debug]task result: Failed
2024-11-07T06:33:07.6264184Z ##[error]Not found testResultFile(s): /home/svc_prc_inttest/azagent/_work/_temp/TestResults/Search/mstest/home/svc_prc_inttest/azagent/_work/r1/a/SearchTests.trx
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Define a classic release pipeline
2. Add the `Publish Test Plan Results` task
3. Set the required properties
4. Set `Test Results Directory` to an absolute path
5. Set `Test Result Files` to a trx file name

**Expected behaviour**

The path is combined correctly and resolves to `<Test Results Directory>/<Test Result Files>`, in my case `/home/svc_prc_inttest/azagent/_work/_temp/TestResults/Search/mstest/SearchTests.trx`

**Workaround**

As a workaround I currently use this:

![image](https://github.com/user-attachments/assets/b9a8b315-6dc0-43ad-b1cc-e573b4368f9e)

This resolves correctly:

```
2024-11-07T06:53:28.6754761Z ##[debug]testResultDirectory=undefined
2024-11-07T06:53:28.6756562Z ##[debug]testResultFiles=/home/svc_prc_inttest/azagent/_work/_temp/TestResults/Search/mstest/SearchTests.trx
2024-11-07T06:53:28.6757867Z ##[debug]check path : /home/svc_prc_inttest/azagent/_work/_temp/TestResults/Search/mstest/SearchTests.trx
```

**Comment by C0nquistadore** [comment]
This is a release pipeline.

``` yaml
variables:
  TargetTestResultsFolderSearch: '$(Agent.TempDirectory)/TestResults/Search'

steps:
- task: PublishTestResults@2
  displayName: 'Publish Search test results'
  inputs:
    testResultsFormat: VSTest
    testResultsFiles: SearchTests.trx
    searchFolder: '$(TargetTestResultsFolderSearch)/mstest'
    testRunTitle: 'Search tests'
    buildPlatform: 'linux-x64'
    buildConfiguration: Release

```

**Comment by bryanbcook** [comment]
I think I see the culprit. Good to know that this is a Release Pipeline, that does influence the default value for the root folder.

**Comment by bryanbcook** [comment]
released in 0.1.16

**Comment by C0nquistadore** [comment]
I have tried this out but it doesn't appear to be fixed on our end.
Here is an updated version of the YAML:
```yaml
steps:
- task: bcook.azdevops-testplan-extension.publishtestplanresults.PublishTestPlanResults@0
  displayName: 'Publish Teams test results'
  inputs:
    accessToken: '$(PublishTestPlanResultsAccessToken)'
    testPlan: 'HL_Master_Integration'
    testResultFormat: mstest
    testResultDirectory: '$(TargetTestResultsFolderLinux)/mstest'
    testResultFiles: TeamsTests.trx
    testRunTitle: 'Teams tests'
```

The configured relative path:
![image](https://github.com/user-attachments/assets/c603d30e-9102-467c-a33f-e17b50ca0a0a)

And the result:
`
2024-11-25T08:47:07.2074996Z ##[debug]testResultFormat=mstest
2024-11-25T08:47:07.2077258Z ##[debug]testResultDirectory=/home/svc_prc_inttest/azagent/_work/_temp/TestResults/mstest
2024-11-25T08:47:07.2078598Z ##[debug]testResultFiles=/home/svc_prc_inttest/azagent/_work/r1/a/TeamsTests.trx
2024-11-25T08:47:07.2081153Z ##[debug]check path : /home/svc_prc_inttest/azagent/_work/_temp/TestResults/mstest/home/svc_prc_inttest/azagent/_work/r1/a/TeamsTests.trx
2024-11-25T08:47:07.2281325Z ##[debug]task result: Failed
`

The relative path is still appended to the current working directory, hence the absolute path for `testResultFiles`.
