### ISSUE TITLE
"name" match strategy only matches xUnit tests with "Description"

### ISSUE THREAD

**Issue by bryanbcook** [bryanbcook/azdevops-testplan-extension#59]
Discovered during regression testing, consider the following scenario:

```yaml
- task: PublishTestPlanResults@1
  inputs:
     testCaseMatchStrategy: name
     testResultFormat: xUnit
     testResultFiles: "path/to/file.xml"
```

Only the first test case is matched correctly.

```csharp
namespace MyNamespace {

  public class MyExample {

     [Fact( Description="The name of the test in the test plan 1")]
     public void ThisMatchesCorrectly() {}

     [Fact] 
     public void The_name_of_the_test_in_the_test_plan_2() {} 
  }
}
```
