### ISSUE TITLE
NUnit Description not matched using "name" matching strategy

### ISSUE THREAD

**Issue by bryanbcook** [bryanbcook/azdevops-testplan-extension#70]
When using NUnit, the description property of a test is not matched.

Test Case:

```csharp
[Test(Description="Match Test Case Using Description")]
public void Match_TestCaseByDisplayNameInsteadOfMethodName()
{
}
```

Pipeline:

```yaml
- task: PublishTestPlanResults@0
  inputs:
    testCaseMatchStrategy: name
    ....
```

Debug output shows the following:

```
Unmatched test cases:
No matching test point found for 'NUnitExample.Tests.Match_TestCaseByDisplayNameInsteadOfMethodName'
```
