### ISSUE TITLE
##[error]TF400813: The user is not authorized to access this resource.

### ISSUE THREAD

**Issue by quotschmacher** [bryanbcook/azdevops-testplan-extension#8]
**Description**

The run of the pipeline stops with the following error: `##[error]TF400813: The user 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' is not authorized to access this resource.`

_provide sample usage of the task, if applicable_
```yaml
steps:
- task: bcook.azdevops-testplan-extension.publishtestplanresults.PublishTestPlanResults@0
  displayName: 'Publish Test Results'
  inputs:
    testPlan: 'UI Test mit Testcafe'
    testResultFormat: xUnit
    testResultDirectory: '$(System.DefaultWorkingDirectory)'
    testResultFiles: 'testcafe/**/report.xml'
```

The result is

```bash
Starting: Publish Test Results
==============================================================================
Task         : Publish Test Plan Results
Description  : Publishes cross-platform test results (xUnit, JUnit) to an Azure DevOps Test Plan
Version      : 0.1.6
Author       : Bryan Cook
Help         : 
==============================================================================
##[error]TF400813: The user 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' is not authorized to access this resource.
Finishing: Publish Test Results

```

With the following environment:
- Pool: [Azure Pipelines]
- Image: ubuntu-22.04
- Agent: Hosted Agent

Tried to run it with multiple users

![image](https://github.com/bryanbcook/azdevops-testplan-extension/assets/50583947/19f2e1c8-abc3-4ad4-af0d-7c028a7e3fc2)

but the error message still prompts the same user id.

**Screenshots**
DId some research and already assured that this option is activated
![image](https://github.com/bryanbcook/azdevops-testplan-extension/assets/50583947/208773ab-e93f-48fb-a954-a58fd5b8d0fa)
