### ISSUE TITLE
Task does not recognize test files using wildcards were not resolved

### ISSUE THREAD

**Issue by bryanbcook** [bryanbcook/azdevops-testplan-extension#98]
It's possible to configure the task to discover test files using a wildcard that does not yield a result.

For non-wildcard files, the task currently validates that the file exists and throws an error. However, in the case of wildcards, the resolution of files is deferred to the [testparser](https://github.com/test-results-reporter/parser) library. Presently, the task does not recognize that no results were resolved from the parser.

Steps to reproduce:

```yaml
- task: PublishTestPlanResults@0
  inputs:
    testPlan: 'My TestPlan'
    testResultFormat: junit
    testResultFiles: '**/non-existent-path/test-results.xml'
```
